"""
Locked event vocabulary for DNS Guard V2.
These are the ONLY event types allowed in the system.
"""

# Lifecycle events (Derived deterministically by Diff Engine)
RE_REGISTRATION = "RE_REGISTRATION"
REGISTRAR_TRANSFER = "REGISTRAR_TRANSFER"
DOMAIN_DROPPED = "DOMAIN_DROPPED"
STATUS_CHANGE = "STATUS_CHANGE"
NAMESERVER_CHANGE = "NAMESERVER_CHANGE"
OWNERSHIP_CHANGED = "OWNERSHIP_CHANGED" # Kept for backwards compatibility / v1 logic

# Security / Intelligence events (Derived by Oracles)
ABUSE_FLAG = "ABUSE_FLAG"
INITIAL_BACKGROUND_ASSESSMENT = "INITIAL_BACKGROUND_ASSESSMENT"
DOMAIN_NON_EXISTENT_AT_QUERY = "DOMAIN_NON_EXISTENT_AT_QUERY"
HISTORICAL_CONTENT_PREVIOUS_TO_CURRENT_REGISTRATION = "HISTORICAL_CONTENT_PREVIOUS_TO_CURRENT_REGISTRATION"
ABUSE_HISTORY_DETECTED = "ABUSE_HISTORY_DETECTED"
ACTIVE_THREAT_DETECTED = "ACTIVE_THREAT_DETECTED"

# Canonical collections
ALL_EVENT_TYPES = {
    RE_REGISTRATION,
    REGISTRAR_TRANSFER,
    DOMAIN_DROPPED,
    STATUS_CHANGE,
    NAMESERVER_CHANGE,
    OWNERSHIP_CHANGED,
    ABUSE_FLAG,
    INITIAL_BACKGROUND_ASSESSMENT,
    DOMAIN_NON_EXISTENT_AT_QUERY,
    HISTORICAL_CONTENT_PREVIOUS_TO_CURRENT_REGISTRATION,
    ABUSE_HISTORY_DETECTED,
    ACTIVE_THREAT_DETECTED,
}

# Events that affect long-term trust
TRUST_RELEVANT_EVENTS = {
    OWNERSHIP_CHANGED,
    ABUSE_FLAG,
    RE_REGISTRATION,
    REGISTRAR_TRANSFER,
    DOMAIN_DROPPED,
    HISTORICAL_CONTENT_PREVIOUS_TO_CURRENT_REGISTRATION,
    ABUSE_HISTORY_DETECTED,
    ACTIVE_THREAT_DETECTED,
}

# Events eligible for blockchain anchoring
ANCHORABLE_EVENTS = {
    OWNERSHIP_CHANGED, # Legacy
    REGISTRAR_TRANSFER,
    RE_REGISTRATION,
    DOMAIN_DROPPED,
    ABUSE_FLAG,
    ABUSE_HISTORY_DETECTED,
    ACTIVE_THREAT_DETECTED,
    INITIAL_BACKGROUND_ASSESSMENT,
}
